IrlFfLeague.Web/Models/ErrorViewModel.cs
using System;

namespace IrlFfLeague.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IrlFfLeague.Web/Models/PickViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using IrlFfLeague.Core.Models;
using IrlFfLeague.Web.Filters;
using IrlFfLeague.Web.Infrastructure;
using IrlFfLeague.Web.Infrastructure.Mapping;

namespace IrlFfLeague.Web.Models
{
    public class PickViewModel : IMapFrom<Pick>
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public int Matchday { get; set; }

        [PopulateSchemesPopulator]
        [UIHint("SimpleDropdown")]
        public Scheme Scheme { get; set; }

        public List<PlayerViewModel> Players { get; set; }
    }
}

IrlFfLeague.Web/Models/PlayerViewModel.cs
using IrlFfLeague.Core.Models;
using IrlFfLeague.Web.Infrastructure.Mapping;

namespace IrlFfLeague.Web.Models
{
    public class PlayerViewModel : IMapFrom<Player>
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

IrlFfLeague.Web/Models/ResultListViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace IrlFfLeague.Web.Models
{
    public class ResultListViewModel
    {
        public string UserName { get; set; }

        public List<int> Points { get; set; }

        public int Total => Points.Sum();
    }
}

IrlFfLeague.Web/Models/ResultViewModel.cs
namespace IrlFfLeague.Web.Models
{
    public class ResultViewModel
    {
    }
}

IrlFfLeague.Web/Models/TeamViewModel.cs
using System.ComponentModel.DataAnnotations;
using IrlFfLeague.Web.Filters;

namespace IrlFfLeague.Web.Models
{
    public class TeamViewModel
    {
        [PopulateUsersPopulator]
        [UIHint("SimpleDropdown")]
        public int User { get; set; }
    }
}

IrlFfLeague.Web/Models/UsersViewModel.cs
using System.ComponentModel.DataAnnotations;
using IrlFfLeague.Web.Filters;

namespace IrlFfLeague.Web.Models
{
    public class UsersViewModel
    {
        [PopulateUsersPopulator]
        [UIHint("SimpleDropdown")]
        public int User { get; set; }
    }
}

IrlFfLeague.Web/Controllers/BaseController.cs
using IrlFfLeague.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace IrlFfLeague.Web.Controllers
{
    [LeaguesPopulator]
    [UsersPopulator]
    [SchemesPopulator]
    public class BaseController : Controller
    {
        
    }
}

IrlFfLeague.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IrlFfLeague.Web.Models;

namespace IrlFfLeague.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IrlFfLeague.Web/Controllers/PickController.cs
using System.Linq;
using AutoMapper.QueryableExtensions;
using IrlFfLeague.Core.Models;
using IrlFfLeague.DataLayer;
using IrlFfLeague.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace IrlFfLeague.Web.Controllers
{
    public class PickController : BaseController
    {
        private readonly IDbContext _context;

        public PickController(IDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new UsersViewModel();

            return View(model);
        }

        public IActionResult Table(int userId, League league)
        {
            var model = _context.Picks.Where(p => p.UserId == userId).OrderByDescending(p => p.Matchday)
                .ProjectTo<PickViewModel>().FirstOrDefault();

            return PartialView(model);
        }
    }
}

IrlFfLeague.Web/Controllers/ResultsController.cs
using IrlFfLeague.DataLayer;
using Microsoft.AspNetCore.Mvc;

namespace IrlFfLeague.Web.Controllers
{
    public class ResultsController : Controller
    {
        private readonly IDbContext _context;

        public ResultsController(IDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Table()
        {
            return View();
        }
    }
}

IrlFfLeague.Web/Controllers/TeamController.cs
using System.Linq;
using IrlFfLeague.Core.Models;
using IrlFfLeague.DataLayer;
using IrlFfLeague.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IrlFfLeague.Web.Controllers
{
    public class TeamController : BaseController
    {
        private readonly IDbContext _context;

        public TeamController(IDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new UsersViewModel();

            return View(model);
        }

        public IActionResult Table(int userId, League league)
        {
            var players = _context.Players.Where(p => p.UserId == userId && p.Club.League == league).OrderBy(p => p.FirstPosition).Select(p =>
                new SelectListItem
                {
                    Text = p.Name,
                    Value = p.Id.ToString()
                }).ToList();

            return PartialView(players);
        }

        [HttpPost]
        public IActionResult AddPlayer(int userId, int playerId)
        {
            var player = _context.Players.SingleOrDefault(p => p.Id == playerId);

            if (player == null)
            {
                return Json(new
                {
                    success = false
                });
            }

            player.UserId = userId;

            _context.Players.Update(player);
            _context.SaveChanges();

            return Json(new
            {
                success = true,
                id = player.Id,
                name = player.Name
            });
        }

        [HttpPost]
        public IActionResult RemovePlayer(int userId, int playerId)
        {
            var player = _context.Players.SingleOrDefault(p => p.Id == playerId);

            if (player == null)
            {
                return Json(new
                {
                    success = false
                });
            }

            player.UserId = null;

            _context.Players.Update(player);
            _context.SaveChanges();

            return Json(new
            {
                success = true
            });
        }

        public IActionResult GetTeams(League league)
        {
            var teams = _context.Clubs.Where(c => c.League == league).OrderBy(c => c.Name).Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString()
            }).ToList();

            return Json(new { teams });
        }

        public IActionResult GetTeamPlayers(int teamId)
        {
            var players = _context.Players.Where(p => p.ClubId == teamId && p.UserId == null).OrderBy(p => p.FirstPosition).Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString()
            }).ToList();

            return Json(new { players });
        }
    }
}

IrlFfLeague.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IrlFfLeague.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IrlFfLeague.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

IrlFfLeague.Web/Views/Pick/Index.cshtml
@using IrlFfLeague.Core.Models
@using IrlFfLeague.Services
@model UsersViewModel

@{
    ViewData["Title"] = "Picks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Teams</h2>

    <div class="row">
        <div class="col-lg-3">
            @Html.EditorFor(m => m.User)
        </div>
    </div>

    <div class="row" id="league-tabs">
        <div class="col-lg-12">
            <ul class="nav nav-tabs" role="tablist">
                @foreach (League league in Enum.GetValues(typeof(League)))
                {
                    var className = (int)league == 0 ? "active" : "";

                    <li role="presentation" class="@className">
                        <a href="#@league.ToString()" aria-controls="@league.ToString()" role="tab" data-id="@((int)league)" data-toggle="tab">@EnumToStringService.LeagueToString(league)</a>
                    </li>
                }
            </ul>
            <div class="tab-content">
                @foreach (League league in Enum.GetValues(typeof(League)))
                {
                    var className = (int)league == 0 ? "active" : "";

                    <div role="tabpanel" class="tab-pane @className" id="@league.ToString()"></div>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="player-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add player</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="player" class="control-label">Player</label>
                        <select class="form-control" id="player"></select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="addPlayer()">Add</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#league-tabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');

            $.get('/Pick/Table?userId=' + $('#User').val() + '&league=' + $(this).data('id'),
                function (data) {
                    $('div.tab-pane.active').html(data);
                });
        });

        $('#User').change(function () {
            $.get('/Pick/Table?userId=' + $(this).val() + '&league=' + $('#league-tabs li.active a').data('id'),
                function (data) {
                    $('div.tab-pane.active').html(data);
                });
        });
    });
</script>

IrlFfLeague.Web/Views/Pick/Table.cshtml
@model PickViewModel

<div class="row">
    <div class="col-lg-12">
        <h3>Matchday @Model.Matchday</h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        @Html.EditorFor(m => m.Scheme)
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table class="table">
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Players)
            {
                if (item == null)
                {
                    continue;
                }

                <tr data-player="@item.Id">
                    <td>@item.Name</td>
                    <td>
                        <button class="btn" onclick="deletePlayer(@item.Id)">Delete</button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

IrlFfLeague.Web/Views/Results/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

IrlFfLeague.Web/Views/Results/Table.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

IrlFfLeague.Web/Views/Shared/EditorTemplates/SimpleDropdown.cshtml
@using System.Collections
@using IrlFfLeague.Web.Helpers
@model object

<div>
    @Html.DropDownListFor(m => Model, new SelectList((IEnumerable)ViewData[Functions.GetPopulateAttributeName(ViewData)], "Value", "Text", Model), "", new { @class = "form-control" })
</div>

IrlFfLeague.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IRL FF League</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IRL FF League</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Pick" asp-action="Index">Picks</a></li>
                    <li><a asp-area="" asp-controller="Team" asp-action="Index">Teams</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Football Fans Club</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

IrlFfLeague.Web/Views/Team/Index.cshtml
@using IrlFfLeague.Core.Models
@using IrlFfLeague.Services
@model UsersViewModel

@{
    ViewData["Title"] = "Teams";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Teams</h2>

    <div class="row">
        <div class="col-lg-3">
            @Html.EditorFor(m => m.User)
        </div>
    </div>

    <div class="row" id="league-tabs">
        <div class="col-lg-12">
            <ul class="nav nav-tabs" role="tablist">
                @foreach (League league in Enum.GetValues(typeof(League)))
                {
                    var className = (int)league == 0 ? "active" : "";

                    <li role="presentation" class="@className">
                        <a href="#@league.ToString()" aria-controls="@league.ToString()" role="tab" data-id="@((int)league)" data-toggle="tab">@EnumToStringService.LeagueToString(league)</a>
                    </li>
                }
            </ul>
            <div class="tab-content">
                @foreach (League league in Enum.GetValues(typeof(League)))
                {
                    var className = (int)league == 0 ? "active" : "";

                    <div role="tabpanel" class="tab-pane @className" id="@league.ToString()"></div>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="player-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add player</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="team" class="control-label">Team</label>
                        <select class="form-control" id="team"></select>
                    </div>
                    <div class="form-group">
                        <label for="player" class="control-label">Player</label>
                        <select class="form-control" id="player"></select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="addPlayer()">Add</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#league-tabs a').click(function(e) {
            e.preventDefault();
            $(this).tab('show');

            $.get('/Team/Table?userId=' + $('#User').val() + '&league=' + $(this).data('id'),
                function (data) {
                    $('div.tab-pane.active').html(data);
                });
        });

        $('#User').change(function () {
            $.get('/Team/Table?userId=' + $(this).val() + '&league=' + $('#league-tabs li.active a').data('id'),
                function(data) {
                    $('div.tab-pane.active').html(data);
                });
        });

        $('#team').change(function () {
            getTeamPlayers($(this).val());
        });
    });

    function addPlayerShowModal() {
        getTeams($('#league-tabs li.active a').data('id'));

        $('#player-modal').modal('show');
    }

    function getTeams(league) {
        $('#team').html('');

        $.get('/Team/GetTeams?league=' + league,
            function (data) {
                for (var i = 0; i < data.teams.length; i++) {
                    $('#team').append('<option value="' + data.teams[i].value + '">' + data.teams[i].text + '</option>');
                }

                getTeamPlayers($('#team').val());
            });
    }

    function getTeamPlayers(team) {
        $('#player').html('');

        $.get('/Team/GetTeamPlayers?teamId=' + team,
            function (data) {
                for (var i = 0; i < data.players.length; i++) {
                    $('#player').append('<option value="' + data.players[i].value + '">' + data.players[i].text + '</option>');
                }
            });
    }

    function addPlayer() {
        $.post('/Team/AddPlayer',
            { userId: $('#User').val(), playerId: $('#player').val() },
            function(data) {
                if (data.success) {
                    $('.table').append('<tr data-player="' + data.id + '">' +
                                            '<td>' + data.name + '</td>' +
                                            '<td>' +
                                            '<button class="btn" onclick="deletePlayer(' + data.id + ')">Delete</button>' +
                                            '</td>' +
                                        '</tr>');

                    $('#player-modal').modal('hide');
                } else {
                    alert('Error!');
                }
            });
    }

    function deletePlayer(playerId) {
        $.post('/Team/RemovePlayer',
            { userId: $('#User').val(), playerId: playerId },
            function(data) {
                if (data.success) {
                    $('tr[data-player=' + playerId + ']').remove();
                } else {
                    alert('Error!');
                }
            });
    }
</script>

IrlFfLeague.Web/Views/Team/Table.cshtml
@model List<SelectListItem>

<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary" onclick="addPlayerShowModal()">Add</button>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table class="table">
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr data-player="@item.Value">
                    <td>@item.Text</td>
                    <td>
                        <button class="btn" onclick="deletePlayer(@item.Value)">Delete</button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>